### ISSUE TITLE
User Guide Issues 

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#214]
- [x] Delete `select` command
- [x] Section 4.6: Formatting issues
- [ ] Task Parameters: 
  - [x] Add a note about deadline parameter allowing past dates
  - [x] A description can be **OF** any value (i.e. alphabet, numbers, special symbols).
  - [x] `Deadline` YYYY-MM-DD not bolded
  - [ ] I think our `Status` changed to `Completed` and `Not Completed` already?
- [x] Task Parameter: Priority level is still not properly explained?
  - Every _how many days_ does it increase? By how much?
  - What if I don't want it to increase every 5 days, but instead every 7 days? : Add a note for this
  - @dominickenn Let's discuss this on Monday if you're still not convinced. Lols. (:
- [ ] Section 4.8: English
  - `Delete a user account to stop using PrioriTask.`
- [ ] Login feature (@dominickenn)
  - [ ] Signup: `p/` and `u/` are interchangable
  - [ ] Section 4.5 and 4.6 should switch.
  - [ ] Addquestion: 
    - [ ] Tell users they can only do that when they're logged in
    - [ ] Encourage users to addquestion when first signed up, once logged in
    - [ ] Can I view a list of all my questions?
    - [ ] What can the parameters take in?
  - [ ] Forgetpassword
    - [ ] Tell users that it'll show a warning if user has no question
    - [ ] Then how is user supposed to retrieve password?
  - [ ] Section 4.6 and 4.7 should be linked. I typed the answer straightaway without following the format because I didn't know there should be one.
  - [ ] Password can take in one digit. Should put a disclaimer that we will solve it.
- [x] Same colour may appear for different tags. After closing and re-opening, the colours may change for that same tag.
- [x] Section 5.5.1 Find tasks whose names, descriptions **OR** deadlines contain any of the given keywords.
- [ ] Toggle command (@aguss787):
  - [x] Change to `completed` and `not completed`
  - [ ] Tell users that if completed, it will show the date instead of `completed`
  - [ ] Can be switch back to `not completed` after being completed
- [ ] Move saving data to FAQ?
- [ ] Section 5.5: Make a `note` box.
- [ ] The user VS you
- [ ] add -> undo -> find -> redo doesn't work

**Comment by dominickenn** [comment]
I added the description of the priority in UG. Please look at it and let me know if its ok.
