### ISSUE TITLE
Should make the toggle command consistent: either complete or done

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#228]
@aguss787 

Either use `complete` or `done`. 
`Task` uses `complete`, subtask uses `done`.

![screen shot 2018-04-08 at 12 07 57 am](https://user-images.githubusercontent.com/24616618/38457293-eaad07bc-3ac0-11e8-9eb3-927f72b083ff.png)

![screen shot 2018-04-08 at 12 06 21 am](https://user-images.githubusercontent.com/24616618/38457282-d78e6be4-3ac0-11e8-8d05-6377adc8cc9e.png)

**Comment by dominickenn** [comment]
Will change it to Completed or Not Completed
