### ISSUE TITLE
Accepts one character passwords

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#236]
@dominickenn 

Should put a disclaimer if we don't solve this by the next user testing.

**Comment by dominickenn** [comment]
Will add a disclaimer that password is your own responsibility

**Comment by guekling** [comment]
LOLS. No. Don't add such a disclaimer! They can still "shoot" us. Should say something like, we understand that this is a security concern, and will resolve this issue in future releases or something. Then tag it with a `coming in v2.0`?

**Comment by dominickenn** [comment]
Think I will just edit the regex instead, seems easier

**Comment by guekling** [comment]
HAHAHA. Okie. Whatever floats your boat. 

Remember to update the UserGuide after you've done that!
