### ISSUE TITLE
Unused Code

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#238]
@natania-d @dominickenn 

The `DateAdded` and `DateCompleted` parameters are not supposed to be typed in by the users, right? So is the `isValidDateAdded` and `isValidDateCompleted` necessary? 

If not, please clear them, and their respective tests. 

Also, please check the rest of the methods, because some of them are copied from the `Deadline` class right? Please change them accordingly if needed (I've edited the `equals()` already because it throws an exception when I made changes to the `Deadline`).

Also, this:
![screen shot 2018-04-08 at 4 09 05 pm](https://user-images.githubusercontent.com/24616618/38464879-5edaba5e-3b47-11e8-91fa-fd8dbe95d232.png)

Thanks! (:

**Comment by dominickenn** [comment]
I think that it just a safety check, although it seems a bit redundant, maybe we could add a logger to the isValidDateAdded and isValidDateCompleted and say that it should never return false.

**Comment by guekling** [comment]
Is it called though? I don't know how you implemented it so I'm not 100% sure if I'm correct, but isn't it only called by the tests? Since `isValidDateCompleted` & the other one is not used by a `DeadlineParser` equivalent?

**Comment by dominickenn** [comment]
Yes its called once, in each of the classes. Although its mainly called in tests, to test it of course. Can we think of it as sort of defensive programming? Acts like an assertion.

**Comment by guekling** [comment]
Ah, okie. I see it. Sorry, overlooked it earlier cos I was in the midst of doing the `Deadline` instead. 

But anyways, this still holds: 
> Also, please check the rest of the methods, because some of them are copied from the Deadline class right?

![screen shot 2018-04-08 at 8 49 48 pm](https://user-images.githubusercontent.com/24616618/38467658-71415460-3b6e-11e8-9de8-34296b7fb180.png)

Found this in `XmlAdaptedTask`. It should have been `this.dateadded` or `this.completed` right?
So if this has been really wrong the entire time, does this means that it's redundant?

**Comment by dominickenn** [comment]
Oh yeh, thats a bug right there. Will rectify.
