### ISSUE TITLE
Priority Level not optional?

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#245]
@dominickenn 

Seeing how priority level is optional, should this be allowed?

![screen shot 2018-04-08 at 5 31 20 pm](https://user-images.githubusercontent.com/24616618/38465787-c00c8586-3b52-11e8-9d84-3ce8ae302e1b.png)

**Comment by dominickenn** [comment]
Think it should be allowed, since if you typed p/ , there is an intention to set priority level

**Comment by guekling** [comment]
Okie. I'll close this then.
